# Get editor completions based on the config schema
#"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
# [character] # The name of the module we are configuring is "character"
# success_symbol = "[ ➜](bold blue)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
style_user = "blue bold"
style_root = "red bold"
show_always = false

[sudo]
style = "bold red"
symbol = " "
disabled = false

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$nodejs\
$cmd_duration $jobs $time\
$line_break\
$character"""

[nodejs]
# format = "[ $symbol($version )]($style)"
format = "[  ($version)](bold green) "

[fill]
symbol = ""

[directory]
home_symbol = "󰌽 ~"
style = "blue"
# read_only = " "
read_only = "  "
truncation_length = 5
truncate_to_repo = false

[character]
success_symbol = "[  ](blue)[❯](white)[❯](red)[❯](yellow)"
error_symbol = "[  ](red)[❯](orange)[❯](red)[❯](orange)"
vicmd_symbol = "[   ](green)[❯](green)[❯](yellow)[❯](purple)"
#error_symbol = "[  ❯](red)"
#vicmd_symbol = "[  ❮](green)"

[git_branch]
symbol = "  "
format = "on [$symbol$branch]($style) "
style = "bold purple"
# truncation_length = 4
# truncation_symbol = "…/"
only_attached = false

[git_commit]
commit_hash_length = 7
format = '[\\($hash$tag\\)]($style) '  # Escapar los paréntesis con \\
style = "bold green"
only_detached = true
tag_disabled = false
tag_symbol = " 🏷 "

[jobs]
symbol = " "
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

# [git_status]
# format = '([\[$all_status$ahead_behind\]]($style) )'
# style = "cyan"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold cyan"
conflicted = " "
up_to_date = "  "
untracked = " "
ahead = "⇡ ${count}"
diverged = "⇕ ⇡${ahead_count}⇣${behind_count}"
behind = "⇣ ${count}"
stashed = " "
modified = "󱦹 "
staged = '[󱕣 \($count\)](green)'
renamed = "󰑕 "
deleted = "󰺝 "

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"
# format = '[\($state( $progress_current of $progress_total)\)]($style) '
# style = "bold yellow"
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"

[git_metrics]
disabled = false
added_style = "bold green"
deleted_style = "bold red"
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[memory_usage]
symbol = " "

[rust]
symbol = " "

# [directory]
# truncation_length = 3
# truncation_symbol = "…/"
# home_symbol = "󱁍 ~"
# read_only_style = "197"
# read_only = "  "
# format = "at [$path]($style)[$read_only]($read_only_style) "



[terraform]
format = "via [ terraform $version]($style)  [$workspace]($style) "

[vagrant]
format = "via [ vagrant $version]($style) "

[docker_context]
format = "via [  $context](bold blue) "

[helm]
format = "via [  $version](bold purple) "

[python]
symbol = " "
python_binary = "python3"

# [node]
# format = "via [ $version](bold green) "
# disabled = false

[ruby]
format = "via [  $version]($style) "

[kubernetes]
format = 'on [ $context\($namespace\)](bold purple) '
disabled = false
[kubernetes.context_aliases]
"clcreative-k8s-staging" = "cl-k8s-staging"
"clcreative-k8s-production" = "cl-k8s-prod"

# [time]
# disabled = false
# style = "bold white"
# format = "[$time]($style)"
